name: Metrics
on:
  schedule: [{cron: "0 * * * *"}] # 毎時実行（自動更新）
  workflow_dispatch:              # 手動実行もできる
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
