name: Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
      - name: Commit and push metrics.svg
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add metrics_renders/github-metrics.svg
          git commit -m "Update GitHub metrics"
          git push
